describe('signup page', () => {
    it('friends_event', () => {
        let date = new Date().toLocaleDateString();
        const [month, day, year] = date.split('/');
        date = `${year}-${month.padStart(2,'0')}-${day.padStart(2,'0')}`;
        cy.visit('/');
        cy.get('#sign_here a').click();
        cy.url().should('include', 'Signup.html');
        cy.stubGeolocation();
        cy.get('#signup_email').type('cypressTheGreat@test.cdy');
        cy.get('#signup_username').type('EventMcEventFace');
        cy.get('#signup_password').type('password');
        cy.get('#signup_pass_conf').type('password');
        cy.get('#signup_button').click();
        cy.url().should('include', 'Map.html');
        cy.get('#settings_button').click();
        cy.url().should('include', 'Settings.html');
        cy.get('#friends_search').select('TestUser');
        cy.window().then((win) => {
            cy.stub(win, 'confirm').returns(true);
            win.alert = () => {};
        });
        cy.get('#add_friends').click();
        cy.get('#logout').click();
        cy.visit('/');
        cy.url().should('eq', 'http://127.0.0.1:8080/');
        cy.location('pathname').should('eq', '/');
        cy.document().its('readyState').should('eq', 'complete');
        cy.stubGeolocation();
        cy.window().then((win) => {
            cy.stub(win, 'alert').as('alert');
        });
        cy.get('#signin_email').type('cypress@test.qin');
        cy.get('#signin_password').type('password');
        cy.get('#signin_button').click();
        cy.url().should('include', 'Map.html');
        cy.get('#calendar_button').should('exist').click();
        cy.url().should('include', 'Calendar.html');
        cy.get('#inbox_button').click();
        cy.get('#accept_friend').first().click();
        cy.get('#close_inbox').click();
        cy.get('#event_button').click();
        cy.get('#title').type('TestEvent');
        cy.get('#more_attendees').click();
        cy.get('input.attendees_select[value="EventMcEventFace"]').check();
        cy.get('#save_attendees').click();
        cy.get('#start').invoke('val', `${date}T05:00`).trigger('input').trigger('change');
        cy.get('#end').invoke('val', `${date}T06:00`).trigger('input').trigger('change');
        cy.get('#location_search').first().select('University Book Store');
        cy.get('#save_event').click();
        cy.contains('.event_name', 'Name: TestEvent').should('exist');
        cy.contains('.month_event', 'TestEvent').should('exist').click();
        cy.window().then((win) => {
            win.alert = () => {};
        });
        cy.contains('.event', 'TestEvent').find('.message_button').click();
        cy.get('#message_text').type('Test Message');
        cy.get('#send_message').click();
        cy.get('#settings_button').click();
        cy.url().should('include', 'Settings.html');
        cy.get('#logout').click();
        cy.visit('/');
        cy.url().should('eq', 'http://127.0.0.1:8080/');
        cy.location('pathname').should('eq', '/');
        cy.document().its('readyState').should('eq', 'complete');
        cy.stubGeolocation();
        cy.window().then((win) => {
            win.alert = () => {};
        });
        cy.get('#signin_email').type('cypressTheGreat@test.cdy');
        cy.get('#signin_password').type('password');
        cy.get('#signin_button').click();
        cy.url().should('include', 'Map.html');
        cy.get('#calendar_button').click();
        cy.url().should('include', 'Calendar.html');
        cy.get('#inbox_button').click();
        cy.get('#accept_event').click();
        cy.get('#close_inbox').click();
        cy.get('#inbox_button').click();
        cy.get('.message').within(() => {
            cy.get('.event_name').should('have.text', 'TestEvent');
            cy.get('.sender_username').should('have.text', '@TestUser');
            cy.get('.message_text').should('have.text', 'Test Message');
        });
        cy.get('#close_inbox').click();
        cy.contains('.event_name', 'Name: TestEvent').should('exist');
        cy.get('#settings_button').click();
        cy.url().should('include', 'Settings.html');
        cy.window().then((win) => {
            cy.stub(win, 'confirm').returns(true);
            win.alert = () => {};
        });
        cy.get('#delete').click();
        cy.url({ timeout: 10000 }).should('eq', 'http://127.0.0.1:8080/');
        cy.visit('/');
        cy.url().should('eq', 'http://127.0.0.1:8080/');
        cy.location('pathname').should('eq', '/');
        cy.document().its('readyState').should('eq', 'complete');
        cy.stubGeolocation();
        cy.window().then((win) => {
            cy.stub(win, 'alert').as('alert');
        });
        cy.get('#signin_email').type('cypress@test.qin');
        cy.get('#signin_password').type('password');
        cy.get('#signin_button').click();
        cy.url().should('include', 'Map.html');
        cy.get('#calendar_button').click();
        cy.url().should('include', 'Calendar.html');
        cy.window().then((win) => {
            cy.stub(win, 'confirm').returns(true);
        });
        cy.contains('.month_event', 'TestEvent').should('exist').click();
        cy.get('.delete_event_btn').click();
        cy.get('.event').should('not.exist');
    });
});